import type { EnemyDef, EnemyId } from '../sim/types';

/** Tuned for zero-leak clears with maze + base DPS (later levels may use research). */
export const ENEMY_DEFS: Record<EnemyId, EnemyDef> = {
  scout: {
    id: 'scout',
    name: 'Scout',
    hp: 14,
    speedCellsPerTick: 0.1,
    bounty: 5,
    leakDamage: 1,
    color: 0xe8c070,
    scale: 0.85,
  },
  grunt: {
    id: 'grunt',
    name: 'Grunt',
    hp: 28,
    speedCellsPerTick: 0.06,
    bounty: 7,
    leakDamage: 1,
    color: 0xc47848,
    scale: 1,
  },
  tank: {
    id: 'tank',
    name: 'Tank',
    hp: 100,
    speedCellsPerTick: 0.034,
    bounty: 16,
    leakDamage: 3,
    color: 0x6a6a78,
    scale: 1.25,
  },
  swarm: {
    id: 'swarm',
    name: 'Swarm',
    hp: 8,
    speedCellsPerTick: 0.1,
    bounty: 2,
    leakDamage: 1,
    color: 0xd4a060,
    scale: 0.7,
  },
  boss: {
    id: 'boss',
    name: 'Boss',
    hp: 320,
    speedCellsPerTick: 0.028,
    bounty: 60,
    leakDamage: 8,
    color: 0xb04040,
    scale: 1.55,
  },
  runner: {
    id: 'runner',
    name: 'Runner',
    hp: 11,
    speedCellsPerTick: 0.13,
    bounty: 6,
    leakDamage: 1,
    color: 0xf0d080,
    scale: 0.8,
  },
  armored: {
    id: 'armored',
    name: 'Armored',
    hp: 160,
    speedCellsPerTick: 0.026,
    bounty: 22,
    leakDamage: 4,
    color: 0x506070,
    scale: 1.35,
  },
  elite: {
    id: 'elite',
    name: 'Elite',
    hp: 70,
    speedCellsPerTick: 0.068,
    bounty: 15,
    leakDamage: 2,
    color: 0xa050c0,
    scale: 1.1,
  },
  carrier: {
    id: 'carrier',
    name: 'Carrier',
    hp: 240,
    speedCellsPerTick: 0.03,
    bounty: 40,
    leakDamage: 5,
    color: 0x708050,
    scale: 1.45,
  },
  raider: {
    id: 'raider',
    name: 'Raider',
    hp: 36,
    speedCellsPerTick: 0.095,
    bounty: 9,
    leakDamage: 2,
    color: 0xd06040,
    scale: 0.95,
  },
};
