import type { TowerDef, TowerId } from '../sim/types';

export const TOWER_DEFS: Record<TowerId, TowerDef> = {
  blocker: {
    id: 'blocker',
    name: 'Wall',
    blurb: 'Cheap maze piece. Blocks path only — no attack.',
    cost: 5,
    blocks: true,
    range: 0,
    damage: 0,
    fireCooldownTicks: 0,
    splash: 0,
    slowFactor: 1,
    slowTicks: 0,
    color: 0xb8a888,
    hotkey: '1',
    spriteKey: 'tower_blocker',
  },
  gun: {
    id: 'gun',
    name: 'Gun',
    blurb: 'Reliable mid-range DPS. Your workhorse turret.',
    cost: 24,
    blocks: true,
    range: 3,
    damage: 12,
    fireCooldownTicks: 10,
    splash: 0,
    slowFactor: 1,
    slowTicks: 0,
    color: 0x5a7fa8,
    hotkey: '2',
    spriteKey: 'tower_gun',
  },
  frost: {
    id: 'frost',
    name: 'Frost',
    blurb: 'Chills creeps in a small splash. Pair with guns.',
    cost: 30,
    blocks: true,
    range: 2,
    damage: 2,
    fireCooldownTicks: 10,
    splash: 1,
    slowFactor: 0.45,
    slowTicks: 50,
    color: 0x7ec8e3,
    hotkey: '3',
    spriteKey: 'tower_frost',
  },
  sniper: {
    id: 'sniper',
    name: 'Sniper',
    blurb: 'Long range, high damage, slow fire. Deletes tanks.',
    cost: 45,
    blocks: true,
    range: 6,
    damage: 32,
    fireCooldownTicks: 28,
    splash: 0,
    slowFactor: 1,
    slowTicks: 0,
    color: 0x8b6bb8,
    hotkey: '4',
    spriteKey: 'tower_sniper',
  },
  mortar: {
    id: 'mortar',
    name: 'Mortar',
    blurb: 'Wide splash for clumps. Weak vs single tanks.',
    cost: 60,
    blocks: true,
    range: 4,
    damage: 12,
    fireCooldownTicks: 26,
    splash: 2,
    slowFactor: 1,
    slowTicks: 0,
    color: 0xc47848,
    hotkey: '5',
    spriteKey: 'tower_mortar',
  },
  spike: {
    id: 'spike',
    name: 'Spike',
    blurb: 'Point-blank shredder. Place on the kill corridor.',
    cost: 16,
    blocks: true,
    range: 1,
    damage: 5,
    fireCooldownTicks: 6,
    splash: 0,
    slowFactor: 1,
    slowTicks: 0,
    color: 0xa06060,
    hotkey: '6',
    spriteKey: 'tower_spike',
  },
  gatling: {
    id: 'gatling',
    name: 'Gatling',
    blurb: 'Ultra-fast short range. Melts swarms in the funnel.',
    cost: 42,
    blocks: true,
    range: 2,
    damage: 3,
    fireCooldownTicks: 4,
    splash: 0,
    slowFactor: 1,
    slowTicks: 0,
    color: 0x6a90b8,
    hotkey: '7',
    spriteKey: 'tower_gun',
    requiresResearch: 'unlock_gatling',
  },
  laser: {
    id: 'laser',
    name: 'Laser',
    blurb: 'Clean mid-range burns. Great vs armored elites.',
    cost: 48,
    blocks: true,
    range: 4,
    damage: 16,
    fireCooldownTicks: 18,
    splash: 0,
    slowFactor: 1,
    slowTicks: 0,
    color: 0xe070a0,
    hotkey: '8',
    spriteKey: 'tower_sniper',
    requiresResearch: 'unlock_laser',
  },
  tesla: {
    id: 'tesla',
    name: 'Tesla',
    blurb: 'Electric splash arcs — crowd control DPS.',
    cost: 55,
    blocks: true,
    range: 3,
    damage: 9,
    fireCooldownTicks: 16,
    splash: 2,
    slowFactor: 1,
    slowTicks: 0,
    color: 0x70d0e8,
    hotkey: '9',
    spriteKey: 'tower_frost',
    requiresResearch: 'unlock_tesla',
  },
  glue: {
    id: 'glue',
    name: 'Glue',
    blurb: 'Heavy slow field. Almost stops runners cold.',
    cost: 40,
    blocks: true,
    range: 2,
    damage: 0,
    fireCooldownTicks: 10,
    splash: 1,
    slowFactor: 0.3,
    slowTicks: 50,
    color: 0xc8b060,
    hotkey: '7',
    spriteKey: 'tower_frost',
    requiresResearch: 'unlock_glue',
  },
  bunker: {
    id: 'bunker',
    name: 'Bunker',
    blurb: 'Hard wall that also shoots at point-blank.',
    cost: 45,
    blocks: true,
    range: 2,
    damage: 10,
    fireCooldownTicks: 16,
    splash: 0,
    slowFactor: 1,
    slowTicks: 0,
    color: 0x8a7a60,
    hotkey: '8',
    spriteKey: 'tower_blocker',
    requiresResearch: 'unlock_bunker',
  },
  beam: {
    id: 'beam',
    name: 'Beam',
    blurb: 'Long sustained fire. Expensive anti-boss tool.',
    cost: 70,
    blocks: true,
    range: 5,
    damage: 11,
    fireCooldownTicks: 10,
    splash: 0,
    slowFactor: 1,
    slowTicks: 0,
    color: 0xd060e0,
    hotkey: '9',
    spriteKey: 'tower_sniper',
    requiresResearch: 'unlock_beam',
  },
};

/** Display / unlock order (base + research towers). */
export const BASE_TOWER_ORDER: TowerId[] = [
  'blocker',
  'gun',
  'frost',
  'sniper',
  'mortar',
  'spike',
  'gatling',
  'laser',
  'tesla',
  'glue',
  'bunker',
  'beam',
];

/** @deprecated use CampaignMeta.unlockedTowerIds — kept for QA defaults */
export const TOWER_ORDER: TowerId[] = [
  'blocker',
  'gun',
  'frost',
  'sniper',
  'mortar',
  'spike',
];

/** Shots per second at 30 tick Hz (0 if non-firing). */
export function towerFireRate(def: TowerDef): number {
  if (def.fireCooldownTicks <= 0) return 0;
  return 30 / def.fireCooldownTicks;
}
